name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/149881676762/locations/global/workloadIdentityPools/github-pool/providers/github-actions"
          service_account: alertchain-deployer@mztn-dep.iam.gserviceaccount.com
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - name: Login to Google Artifact Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and push Docker image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          tags: asia-northeast1-docker.pkg.dev/mztn-dep/service-images/alertchain:${{ github.sha }}
      - name: Deploy to Cloud Run
        run: |
          gcloud beta run deploy alertchain \
            --image=asia-northeast1-docker.pkg.dev/mztn-dep/service-images/alertchain:${{ github.sha }} \
            --region=asia-northeast1 \
            --platform=managed \
            --port 8080 \
            --allow-unauthenticated \
            --ingress=all \
            --set-env-vars "
              ALERTCHAIN_ADDR=0.0.0.0:8080,
              ALERTCHAIN_POLICY_DIR=/policy,
              ALERTCHAIN_ENABLE_PRINT=1,
              ALERTCHAIN_DB_TYPE=firestore,
              ALERTCHAIN_FIRESTORE_PROJECT_ID=mztn-dep,
              ALERTCHAIN_FIRESTORE_COLLECTION_PREFIX=alertchain,
              ALERTCHAIN_LOG_FORMAT=json,
              SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}
            " \
            --args serve \
            --service-account=alertchain@mztn-dep.iam.gserviceaccount.com
