name: deploy

on:
  push:
    branches:
      - main

jobs:
  gsls:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/149881676762/locations/global/workloadIdentityPools/alertchain-deployer/providers/github"
          service_account: alertchain-deployer@mztn-dep.iam.gserviceaccount.com
